---
- block:
  - name: create caddy configs directory
    file:
      path: "{{ crabby_caddy_root_path }}/config"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: create caddy state directory
    file:
      path: "{{ crabby_caddy_root_path }}/.caddy"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: deploy caddy file
    template:
      src: Caddyfile.j2
      dest: "{{ crabby_caddy_root_path }}/config/Caddyfile"
      owner: root
      group: root
      mode: 0640
    notify: restart docker services
  when: is_selenium_caddy

- name: create compose directory
  file:
    path: /srv/docker-crabby
    state: directory
    owner: root
    group: root
    mode: 0755

- name: deploy compose file
  template:
    src: "{{ crabby_compose_template }}"
    dest: /srv/docker-crabby/docker-compose.yml
    owner: root
    group: root
    mode: 0644
  notify: restart docker services

- name: start docker services
  docker_service:
    project_src: /srv/docker-crabby
