---
# tasks file for ansible-role-crabby
- name: Set facts
  include_tasks: set_facts.yml

- block:
  - name: Setup prereqs
    include_tasks: prereqs.yml

  - name: Run setup
    include_tasks: setup.yml

  - name: Install crabby
    include_tasks: install.yml

  - name: Setup configs
    include_tasks: config.yml

  - name: Setup services
    include_tasks: service.yml
  when: is_crabby

- name: Deploy compose
  include_tasks: compose.yml
