---
# tasks file for ansible-role-crabby
- name: Set is_crabby if in crabby group
  set_fact:
    is_crabby: "{{ inventory_hostname in groups['crabby'] | default([]) }}"

- name: Set is_selenium_agent if in selenium_agent group
  set_fact:
    is_selenium_agent: "{{ inventory_hostname in groups['selenium_agent'] | default([]) }}"

- name: Set is_phantomjs_agent if in selenium_agent group
  set_fact:
    is_phantomjs_agent: "{{ inventory_hostname in groups['phantomjs_agent'] | default([]) }}"

- name: Setup prereqs
  include_tasks: prereqs.yml
  when: is_crabby
  tags:
    - install

- name: Install crabby
  include_tasks: install.yml
  when: is_crabby
  tags:
    - install

- name: Setup configs
  include_tasks: config.yml
  when: is_crabby
  tags:
    - config

- name: Setup services
  include_tasks: service.yml
  when: is_crabby
  tags:
    - config

- name: Setup compose agents
  include_tasks: compose.yml
  when: is_selenium_agent or is_phantomjs_agent
  tags:
    - install