---
# tasks file for ansible-role-crabby
- name: Set facts
  include_tasks: set_facts.yml

- name: Setup prereqs
  include_tasks: prereqs.yml
  when: is_crabby

- name: Install crabby
  include_tasks: install.yml
  when: is_crabby

- name: Setup configs
  include_tasks: config.yml
  when: is_crabby

- name: Setup services
  include_tasks: service.yml
  when: is_crabby

- name: Deploy compose
  include_tasks: compose.yml
