---
# handlers file for ansible-role-crabby
- name: restart crabby
  service:
    name: crabby
    state: restarted

- name: restart docker services
  docker_service:
    project_src: /srv/docker-crabby
    restarted: yes